"""initial migration up

Revision ID: 10d6a87ab66f
Revises: 51f3879f1f1b
Create Date: 2026-01-31 21:59:38.854720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d6a87ab66f'
down_revision: Union[str, Sequence[str], None] = '51f3879f1f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_intelligence',
    sa.Column('content_hash', sa.String(length=128), nullable=False, comment='文件内容权威Hash (通常为OSS ETag)'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='intelligencestatus'), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True, comment='AI分析结果'),
    sa.Column('is_vector_indexed', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('content_hash', name=op.f('pk_assets_intelligence'))
    )
    op.create_index(op.f('ix_assets_intelligence_is_vector_indexed'), 'assets_intelligence', ['is_vector_indexed'], unique=False)
    op.create_table('assets_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_assets_folders_creator_id_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['assets_folders.id'], name=op.f('fk_assets_folders_parent_id_assets_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['ai_workspaces.id'], name=op.f('fk_assets_folders_workspace_id_ai_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets_folders'))
    )
    op.create_index(op.f('ix_assets_folders_is_deleted'), 'assets_folders', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_folders_parent_id'), 'assets_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_assets_folders_uuid'), 'assets_folders', ['uuid'], unique=True)
    op.create_index(op.f('ix_assets_folders_workspace_id'), 'assets_folders', ['workspace_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('real_name', sa.String(length=1024), nullable=False, comment='存储桶中的完整物理Key'),
    sa.Column('url', sa.String(length=2048), nullable=False, comment='访问URL'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', 'OTHER', name='assettype'), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'ARCHIVED', name='assetstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_hash'], ['assets_intelligence.content_hash'], name=op.f('fk_assets_content_hash_assets_intelligence')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_assets_creator_id_users')),
    sa.ForeignKeyConstraint(['folder_id'], ['assets_folders.id'], name=op.f('fk_assets_folder_id_assets_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['ai_workspaces.id'], name=op.f('fk_assets_workspace_id_ai_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_content_hash'), 'assets', ['content_hash'], unique=False)
    op.create_index(op.f('ix_assets_folder_id'), 'assets', ['folder_id'], unique=False)
    op.create_index(op.f('ix_assets_is_deleted'), 'assets', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_index(op.f('ix_assets_uuid'), 'assets', ['uuid'], unique=True)
    op.create_index(op.f('ix_assets_workspace_id'), 'assets', ['workspace_id'], unique=False)
    op.add_column('ai_workspaces', sa.Column('asset_config', sa.JSON(), nullable=True, comment='素材库策略配置'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_workspaces', 'asset_config')
    op.drop_index(op.f('ix_assets_workspace_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_uuid'), table_name='assets')
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_is_deleted'), table_name='assets')
    op.drop_index(op.f('ix_assets_folder_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_content_hash'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_assets_folders_workspace_id'), table_name='assets_folders')
    op.drop_index(op.f('ix_assets_folders_uuid'), table_name='assets_folders')
    op.drop_index(op.f('ix_assets_folders_parent_id'), table_name='assets_folders')
    op.drop_index(op.f('ix_assets_folders_is_deleted'), table_name='assets_folders')
    op.drop_table('assets_folders')
    op.drop_index(op.f('ix_assets_intelligence_is_vector_indexed'), table_name='assets_intelligence')
    op.drop_table('assets_intelligence')
    # ### end Alembic commands ###
