"""initial migration up

Revision ID: 51f3879f1f1b
Revises: 3368066de63d
Create Date: 2026-01-28 22:53:18.017368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f3879f1f1b'
down_revision: Union[str, Sequence[str], None] = '3368066de63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_agent_context_summaries', sa.Column('ref_created_at', sa.DateTime(), nullable=True, comment='原始对话轮次的发生时间'))
    op.create_index(op.f('ix_ai_agent_context_summaries_ref_created_at'), 'ai_agent_context_summaries', ['ref_created_at'], unique=False)
    op.add_column('ai_chat_sessions', sa.Column('message_count', sa.Integer(), nullable=False, comment='正常消息数量'))
    op.create_foreign_key(op.f('fk_ai_projects_main_resource_id_ai_resources'), 'ai_projects', 'ai_resources', ['main_resource_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_ai_resources_workspace_instance_id_ai_resource_instances'), 'ai_resources', 'ai_resource_instances', ['workspace_instance_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_ai_resources_latest_published_instance_id_ai_resource_instances'), 'ai_resources', 'ai_resource_instances', ['latest_published_instance_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_service_module_types_default_version_id_service_module_versions'), 'service_module_types', 'service_module_versions', ['default_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_service_modules_latest_version_id_service_module_versions'), 'service_modules', 'service_module_versions', ['latest_version_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_traces_parent_span_uuid_traces'), 'traces', 'traces', ['parent_span_uuid'], ['span_uuid'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_traces_parent_span_uuid_traces'), 'traces', type_='foreignkey')
    op.drop_constraint(op.f('fk_service_modules_latest_version_id_service_module_versions'), 'service_modules', type_='foreignkey')
    op.drop_constraint(op.f('fk_service_module_types_default_version_id_service_module_versions'), 'service_module_types', type_='foreignkey')
    op.drop_constraint(op.f('fk_ai_resources_latest_published_instance_id_ai_resource_instances'), 'ai_resources', type_='foreignkey')
    op.drop_constraint(op.f('fk_ai_resources_workspace_instance_id_ai_resource_instances'), 'ai_resources', type_='foreignkey')
    op.drop_constraint(op.f('fk_ai_projects_main_resource_id_ai_resources'), 'ai_projects', type_='foreignkey')
    op.drop_column('ai_chat_sessions', 'message_count')
    op.drop_index(op.f('ix_ai_agent_context_summaries_ref_created_at'), table_name='ai_agent_context_summaries')
    op.drop_column('ai_agent_context_summaries', 'ref_created_at')
    # ### end Alembic commands ###
