"""initial migration up

Revision ID: b0cd9c56f0b2
Revises: 10d6a87ab66f
Create Date: 2026-02-01 20:08:11.667443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0cd9c56f0b2'
down_revision: Union[str, Sequence[str], None] = '10d6a87ab66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_uiapps',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('global_config', sa.JSON(), nullable=False, comment='全局配置'),
    sa.Column('navigation', sa.JSON(), nullable=True, comment='导航菜单定义'),
    sa.Column('home_page_uuid', sa.String(length=64), nullable=True, comment='默认首页的Page UUID'),
    sa.ForeignKeyConstraint(['version_id'], ['ai_resource_instances.id'], name=op.f('fk_ai_uiapps_version_id_ai_resource_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_ai_uiapps'))
    )
    op.create_table('ai_uiapp_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_version_id', sa.Integer(), nullable=False),
    sa.Column('page_uuid', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False, comment='路由路径, e.g. /dashboard'),
    sa.Column('label', sa.String(length=255), nullable=False, comment='页面标题'),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False, comment='组件树 DSL'),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['app_version_id'], ['ai_uiapps.version_id'], name=op.f('fk_ai_uiapp_pages_app_version_id_ai_uiapps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_uiapp_pages')),
    sa.UniqueConstraint('app_version_id', 'page_uuid', name='uq_uiapp_version_page'),
    sa.UniqueConstraint('app_version_id', 'path', name='uq_uiapp_version_path')
    )
    op.create_index(op.f('ix_ai_uiapp_pages_app_version_id'), 'ai_uiapp_pages', ['app_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_uiapp_pages_app_version_id'), table_name='ai_uiapp_pages')
    op.drop_table('ai_uiapp_pages')
    op.drop_table('ai_uiapps')
    # ### end Alembic commands ###
